### ISSUE TITLE
How to use with stable diffusion repo?

### ISSUE THREAD

**Issue by Nughu** [rinongal/textual_inversion#103]
I have stable diffusion locally in a separate directory, working fine with the v1.4 ckpt. I generated embeddings.pt using textual inversion. How can I add the embedding to stable diffusion itself? There is no option for "embedding_path" in stable diffusion's txt2img.py.

**Comment by rinongal** [comment]
You need to use the stable_txt2img.py file in our scripts directory. See the txt2img.py example in our readme for example arguments.

**Comment by xlc-github** [comment]
@rinongal  hello,I follow the redeme and I also want to use stable diffusion repo with embeddings.pt,but i encountered an error.here is the error:
“AttributeError: 'LatentDiffusion' object has no attribute 'embedding_manager'”，when I load the embedings.pt.so where should I update,thanks

**Comment by xlc-github** [comment]
> You need to use the stable_txt2img.py file in our scripts directory. See the txt2img.py example in our readme for example arguments.

hi,I have do this follow  your advise.And I have use a "embedding.pt" which I had pre-trained,but the result of my test is not the expected style.does the sd model is not support this embedding mode? Thanks

**Comment by rinongal** [comment]
Your training log directory should have examples of images generated using your style. Can you look there and see that the samples_scaled images make sense to you?

**Comment by rinongal** [comment]
Closing due to lack of activity. Feel free to reopen if you need more help.
